
var g;g||(g=typeof Module !== 'undefined' ? Module : {});g.Vf||(g.Vf=0);g.Vf++;
(function(a){function b(m,r,t){var u=new XMLHttpRequest;u.open("GET",m,!0);u.responseType="arraybuffer";u.onprogress=function(w){var y=r;w.total&&(y=w.total);if(w.loaded){u.jf?g.tf[m].loaded=w.loaded:(u.jf=!0,g.tf||(g.tf={}),g.tf[m]={loaded:w.loaded,total:y});var B=y=w=0,D;for(D in g.tf){var H=g.tf[D];w+=H.total;y+=H.loaded;B++}w=Math.ceil(w*g.Vf/B);g.setStatus&&g.setStatus("Downloading data... ("+y+"/"+w+")")}else!g.tf&&g.setStatus&&g.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+
m);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)t(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}function c(m){console.error("package error:",m)}function d(){function m(w,y,B){this.start=w;this.end=y;this.audio=B}function r(w){if(!w)throw"Loading data file failed."+Error().stack;if(!(w instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;w=new Uint8Array(w);m.prototype.Dg=w;w=a.files;for(var y=
0;y<w.length;++y)m.prototype.jf[w[y].filename].onload();g.removeRunDependency("datafile_build/web/index.data")}g.FS_createPath("/","assets",!0,!0);m.prototype={jf:{},open:function(w,y){this.name=y;this.jf[y]=this;g.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.Qf(this.Dg.subarray(this.start,this.end))},Qf:function(w){g.FS_createDataFile(this.name,null,w,!0,!0,!0);g.removeRunDependency("fp "+this.name);this.jf[this.name]=null}};for(var t=a.files,u=0;u<t.length;++u)(new m(t[u].start,
t[u].end,t[u].audio)).open("GET",t[u].filename);g.addRunDependency("datafile_build/web/index.data");g.qg||(g.qg={});g.qg["build/web/index.data"]={bh:!1};l?(r(l),l=null):k=r}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";
"function"!==typeof g.locateFilePackage||g.locateFile||(g.locateFile=g.locateFilePackage,h("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=g.locateFile?g.locateFile("index.data",""):"index.data",f=a.remote_package_size,k=null,l=g.getPreloadedPackage?g.getPreloadedPackage(e,f):null;l||b(e,f,function(m){k?(k(m),k=null):l=m},c);g.calledRun?d():(g.preRun||(g.preRun=[]),g.preRun.push(d))})({files:[{filename:"/assets/atlas.dat",
start:0,end:215,audio:0},{filename:"/assets/atlas.png",start:215,end:2927,audio:0}],remote_package_size:2927,package_uuid:"6e340844-682f-461a-aacc-cd7d4e02df77"});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ja=!fa&&!ia&&!ha;
var n="",ka,la,ma,na,oa;
if(ia)n=ha?require("path").dirname(n)+"/":__dirname+"/",ka=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=ka(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",
p),ea=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ja)"undefined"!=typeof read&&(ka=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?n=self.location.href:"undefined"!==typeof document&&document.currentScript&&(n=document.currentScript.src),n=0!==n.indexOf("blob:")?n.substr(0,n.lastIndexOf("/")+1):"",ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
la=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var qa=g.print||console.log.bind(console),h=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);function ra(a){sa||(sa={});sa[a]||(sa[a]=1,h(a))}var sa,ta;g.wasmBinary&&(ta=g.wasmBinary);
var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&p("no native wasm support detected");
function ua(a,b,c){c=c||"i8";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":va[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":wa=[b>>>0,(x=b,1<=+Math.abs(x)?0<x?(Math.min(+Math.floor(x/4294967296),4294967295)|0)>>>0:~~+Math.ceil((x-+(~~x>>>0))/4294967296)>>>0:0)];v[a>>2]=wa[0];v[a+4>>2]=wa[1];break;case "float":z[a>>2]=b;break;case "double":xa[a>>3]=b;break;default:p("invalid type for setValue: "+c)}}var ya,za=!1,Aa;
function assert(a,b){a||p("Assertion failed: "+b)}function Ba(a){var b=Ca(a.length);a.subarray||a.slice?A.set(a,b):A.set(new Uint8Array(a),b);return b}var Ea="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Fa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ea)return Ea.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?Fa(A,a,b):""}
function E(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Ga(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ha(a){var b=Ga(a)+1,c=Ia(b);E(a,q,c,b);return c}var Ja,q,A,va,Ka,v,F,z,xa;
function La(){var a=ya.buffer;Ja=a;g.HEAP8=q=new Int8Array(a);g.HEAP16=va=new Int16Array(a);g.HEAP32=v=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=Ka=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=z=new Float32Array(a);g.HEAPF64=xa=new Float64Array(a)}var G,Ma=[],Na=[],Oa=[],Pa=[];function Qa(){var a=g.preRun.shift();Ma.unshift(a)}var Ra=0,Sa=null,Ta=null;function Ua(){Ra++;g.monitorRunDependencies&&g.monitorRunDependencies(Ra)}
function Va(){Ra--;g.monitorRunDependencies&&g.monitorRunDependencies(Ra);if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}g.preloadedImages={};g.preloadedAudios={};function p(a){if(g.onAbort)g.onAbort(a);h(a);za=!0;Aa=1;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Wa(){return I.startsWith("data:application/octet-stream;base64,")}var I="index.wasm";if(!Wa()){var Xa=I;I=g.locateFile?g.locateFile(Xa,n):n+Xa}
function Ya(){var a=I;try{if(a==I&&ta)return new Uint8Array(ta);if(ma)return ma(a);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function Za(){if(!ta&&(fa||ha)){if("function"===typeof fetch&&!I.startsWith("file://"))return fetch(I,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+I+"'";return a.arrayBuffer()}).catch(function(){return Ya()});if(la)return new Promise(function(a,b){la(I,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ya()})}
var x,wa,bb={23960:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},24097:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?1:0},24321:function(a){var b=g.SDL2;if(a){void 0!==b.capture.xf&&clearTimeout(b.capture.xf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.hf&&(b.capture.hf.onaudioprocess=function(){},b.capture.hf.disconnect(),b.capture.hf=void 0);void 0!==b.capture.Hf&&(b.capture.Hf.disconnect(),b.capture.Hf=void 0);void 0!==b.capture.Nf&&(b.capture.Nf=void 0);b.capture=void 0}else void 0!=b.audio.hf&&(b.audio.hf.disconnect(),b.audio.hf=void 0),b.audio=void 0;void 0!==b.ff&&void 0===b.audio&&void 0===b.capture&&(b.ff.close(),b.ff=void 0)},25493:function(a){"undefined"===typeof g.SDL2&&(g.SDL2={});var b=g.SDL2;
a?b.capture={}:b.audio={};b.ff||("undefined"!==typeof AudioContext?b.ff=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ff=new webkitAudioContext),b.ff&&$a(b.ff));return void 0===b.ff?-1:0},25986:function(){return g.SDL2.ff.sampleRate},26054:function(a,b,c,d){function e(){}function f(l){void 0!==k.capture.xf&&(clearTimeout(k.capture.xf),k.capture.xf=void 0);k.capture.Hf=k.ff.createMediaStreamSource(l);k.capture.hf=k.ff.createScriptProcessor(b,a,1);k.capture.hf.onaudioprocess=function(m){void 0!==
k&&void 0!==k.capture&&(m.outputBuffer.getChannelData(0).fill(0),k.capture.Rf=m.inputBuffer,ab(c,[d]))};k.capture.Hf.connect(k.capture.hf);k.capture.hf.connect(k.ff.destination);k.capture.stream=l}var k=g.SDL2;k.capture.Nf=k.ff.createBuffer(a,b,k.ff.sampleRate);k.capture.Nf.getChannelData(0).fill(0);k.capture.xf=setTimeout(function(){k.capture.Rf=k.capture.Nf;ab(c,[d])},b/k.ff.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,
video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},27706:function(a,b,c,d){var e=g.SDL2;e.audio.hf=e.ff.createScriptProcessor(b,0,a);e.audio.hf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.gg=f.outputBuffer,ab(c,[d]))};e.audio.hf.connect(e.ff.destination)},28116:function(a,b){for(var c=g.SDL2,d=c.audio.gg.numberOfChannels,e=0;e<d;++e){var f=c.audio.gg.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+
f.length+" samples vs expected "+b+" samples!";for(var k=0;k<b;++k)f[k]=z[a+(k*d+e<<2)>>2]}},28596:function(a,b){for(var c=g.SDL2,d=c.capture.Rf.numberOfChannels,e=0;e<d;++e){var f=c.capture.Rf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var k=0;k<b;++k)ua(a+4*k,f[k],"float");else for(k=0;k<b;++k)ua(a+4*(k*d+e),f[k],"float")}}};function cb(a,b,c){a.addEventListener(b,c,{once:!0})}
function $a(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&cb(d,c,function(){"suspended"===a.state&&a.resume()})})})}function eb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Fg;"number"===typeof c?void 0===b.zf?G.get(c)():G.get(c)(b.zf):c(void 0===b.zf?null:b.zf)}}}
function ab(a,b){if("vi".includes("j")){var c=g.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else G.get(a).apply(null,b)}function fb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function gb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ib(a){if("/"===a)return"/";a=gb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function jb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ia)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){p("randomDevice")}}
function kb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var lb=[];function mb(a,b){lb[a]={input:[],output:[],vf:b};nb(a,ob)}
var ob={open:function(a){var b=lb[a.node.rdev];if(!b)throw new J(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.vf.flush(a.tty)},flush:function(a){a.tty.vf.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.vf.kg)throw new J(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.vf.kg(a.tty)}catch(l){throw new J(29);}if(void 0===k&&0===e)throw new J(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.vf.$f)throw new J(60);
try{for(var e=0;e<d;e++)a.tty.vf.$f(a.tty,b[c+e])}catch(f){throw new J(29);}d&&(a.node.timestamp=Date.now());return e}},qb={kg:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.jf?Buffer.jf(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=pb(b,!0)}return a.input.shift()},$f:function(a,b){null===b||10===b?(qa(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Fa(a.output,0)),a.output=[])}},rb={$f:function(a,b){null===b||10===b?(h(Fa(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(h(Fa(a.output,0)),a.output=[])}},K={nf:null,pf:function(){return K.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new J(63);K.nf||(K.nf={dir:{node:{qf:K.df.qf,lf:K.df.lf,lookup:K.df.lookup,If:K.df.If,rename:K.df.rename,unlink:K.df.unlink,rmdir:K.df.rmdir,readdir:K.df.readdir,symlink:K.df.symlink},stream:{rf:K.cf.rf}},file:{node:{qf:K.df.qf,lf:K.df.lf},stream:{rf:K.cf.rf,read:K.cf.read,write:K.cf.write,cg:K.cf.cg,Jf:K.cf.Jf,Lf:K.cf.Lf}},link:{node:{qf:K.df.qf,lf:K.df.lf,readlink:K.df.readlink},stream:{}},fg:{node:{qf:K.df.qf,
lf:K.df.lf},stream:sb}});c=tb(a,b,c,d);16384===(c.mode&61440)?(c.df=K.nf.dir.node,c.cf=K.nf.dir.stream,c.bf={}):32768===(c.mode&61440)?(c.df=K.nf.file.node,c.cf=K.nf.file.stream,c.ef=0,c.bf=null):40960===(c.mode&61440)?(c.df=K.nf.link.node,c.cf=K.nf.link.stream):8192===(c.mode&61440)&&(c.df=K.nf.fg.node,c.cf=K.nf.fg.stream);c.timestamp=Date.now();a&&(a.bf[b]=c,a.timestamp=c.timestamp);return c},dh:function(a){return a.bf?a.bf.subarray?a.bf.subarray(0,a.ef):new Uint8Array(a.bf):new Uint8Array(0)},
hg:function(a,b){var c=a.bf?a.bf.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.bf,a.bf=new Uint8Array(b),0<a.ef&&a.bf.set(c.subarray(0,a.ef),0))},Rg:function(a,b){if(a.ef!=b)if(0==b)a.bf=null,a.ef=0;else{var c=a.bf;a.bf=new Uint8Array(b);c&&a.bf.set(c.subarray(0,Math.min(b,a.ef)));a.ef=b}},df:{qf:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===
(a.mode&61440)?b.size=a.ef:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ag=4096;b.blocks=Math.ceil(b.size/b.Ag);return b},lf:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Rg(a,b.size)},lookup:function(){throw ub[44];},If:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=vb(b,
c)}catch(f){}if(d)for(var e in d.bf)throw new J(55);}delete a.parent.bf[a.name];a.parent.timestamp=Date.now();a.name=c;b.bf[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.bf[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=vb(a,b),d;for(d in c.bf)throw new J(55);delete a.bf[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.bf)a.bf.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},
readlink:function(a){if(40960!==(a.mode&61440))throw new J(28);return a.link}},cf:{read:function(a,b,c,d,e){var f=a.node.bf;if(e>=a.node.ef)return 0;a=Math.min(a.node.ef-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===q.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.bf||a.bf.subarray)){if(f)return a.bf=b.subarray(c,c+d),a.ef=d;if(0===a.ef&&0===e)return a.bf=b.slice(c,c+d),a.ef=
d;if(e+d<=a.ef)return a.bf.set(b.subarray(c,c+d),e),d}K.hg(a,e+d);if(a.bf.subarray&&b.subarray)a.bf.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.bf[e+f]=b[c+f];a.ef=Math.max(a.ef,e+d);return d},rf:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ef);if(0>b)throw new J(28);return b},cg:function(a,b,c){K.hg(a.node,b+c);a.node.ef=Math.max(a.node.ef,b+c)},Jf:function(a,b,c,d,e,f){if(0!==b)throw new J(28);if(32768!==(a.node.mode&61440))throw new J(43);a=a.node.bf;if(f&
2||a.buffer!==Ja){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=Ca(f);c<f;)q[b+c++]=0;c=b;if(!c)throw new J(48);q.set(a,c)}else d=!1,c=a.byteOffset;return{Pg:c,Pf:d}},Lf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new J(43);if(e&2)return 0;K.cf.write(a,b,0,d,c,!1);return 0}}},wb=null,xb={},yb=[],zb=1,Ab=null,Bb=!0,Cb={},J=null,ub={};
function Db(a,b){a=kb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ig:!0,ag:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.ag)throw new J(32);a=fb(a.split("/").filter(function(k){return!!k}),!1);var e=wb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=vb(e,a[d]);c=gb(c+"/"+a[d]);e.wf&&(!f||f&&b.ig)&&(e=e.wf.root);if(!f||b.Wf)for(f=0;40960===(e.mode&61440);)if(e=Eb(c),c=kb(hb(c),e),e=Db(c,{ag:b.ag}).node,40<f++)throw new J(32);}return{path:c,node:e}}
function Fb(a){for(var b;;){if(a===a.parent)return a=a.pf.og,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ab.length}function vb(a,b){var c;if(c=(c=Hb(a,"x"))?c:a.df.lookup?0:2)throw new J(c,a);for(c=Ab[Gb(a.id,b)];c;c=c.uf){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.df.lookup(a,b)}
function tb(a,b,c,d){a=new Ib(a,b,c,d);b=Gb(a.parent.id,a.name);a.uf=Ab[b];return Ab[b]=a}var Jb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Kb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Hb(a,b){if(Bb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Lb(a,b){try{return vb(a,b),20}catch(c){}return Hb(a,"wx")}
function Mb(a){var b=4096;for(a=a||0;a<=b;a++)if(!yb[a])return a;throw new J(33);}function Nb(a,b){Ob||(Ob=function(){},Ob.prototype={});var c=new Ob,d;for(d in a)c[d]=a[d];a=c;b=Mb(b);a.fd=b;return yb[b]=a}var sb={open:function(a){a.cf=xb[a.node.rdev].cf;a.cf.open&&a.cf.open(a)},rf:function(){throw new J(70);}};function nb(a,b){xb[a]={cf:b}}
function Pb(a,b){var c="/"===b,d=!b;if(c&&wb)throw new J(10);if(!c&&!d){var e=Db(b,{ig:!1});b=e.path;e=e.node;if(e.wf)throw new J(10);if(16384!==(e.mode&61440))throw new J(54);}b={type:a,kh:{},og:b,Ng:[]};a=a.pf(b);a.pf=b;b.root=a;c?wb=a:e&&(e.wf=b,e.pf&&e.pf.Ng.push(b))}function Qb(a,b,c){var d=Db(a,{parent:!0}).node;a=ib(a);if(!a||"."===a||".."===a)throw new J(28);var e=Lb(d,a);if(e)throw new J(e);if(!d.df.If)throw new J(63);return d.df.If(d,a,b,c)}function L(a){return Qb(a,16895,0)}
function Rb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Qb(a,b|8192,c)}function Sb(a,b){if(!kb(a))throw new J(44);var c=Db(b,{parent:!0}).node;if(!c)throw new J(44);b=ib(b);var d=Lb(c,b);if(d)throw new J(d);if(!c.df.symlink)throw new J(63);c.df.symlink(c,b,a)}
function Tb(a){var b=Db(a,{parent:!0}).node,c=ib(a),d=vb(b,c);a:{try{var e=vb(b,c)}catch(k){e=k.kf;break a}var f=Hb(b,"wx");e=f?f:16384===(e.mode&61440)?31:0}if(e)throw new J(e);if(!b.df.unlink)throw new J(63);if(d.wf)throw new J(10);try{Cb.willDeletePath&&Cb.willDeletePath(a)}catch(k){h("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+k.message)}b.df.unlink(b,c);b=Gb(d.parent.id,d.name);if(Ab[b]===d)Ab[b]=d.uf;else for(b=Ab[b];b;){if(b.uf===d){b.uf=d.uf;break}b=b.uf}try{if(Cb.onDeletePath)Cb.onDeletePath(a)}catch(k){h("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+k.message)}}function Eb(a){a=Db(a).node;if(!a)throw new J(44);if(!a.df.readlink)throw new J(28);return kb(Fb(a.parent),a.df.readlink(a))}function Ub(a,b){a="string"===typeof a?Db(a,{Wf:!0}).node:a;if(!a.df.lf)throw new J(63);a.df.lf(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Vb(a,b,c,d){if(""===a)throw new J(44);if("string"===typeof b){var e=Jb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=gb(a);try{f=Db(a,{Wf:!(b&131072)}).node}catch(k){}}e=!1;if(b&64)if(f){if(b&128)throw new J(20);}else f=Qb(a,c,0),e=!0;if(!f)throw new J(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new J(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Kb(b)||b&512)?31:Hb(f,Kb(b)):44))throw new J(c);if(b&512){c=f;c="string"===typeof c?Db(c,{Wf:!0}).node:c;if(!c.df.lf)throw new J(63);if(16384===(c.mode&61440))throw new J(31);if(32768!==(c.mode&61440))throw new J(28);if(e=Hb(c,"w"))throw new J(e);c.df.lf(c,{size:0,timestamp:Date.now()})}b&=-131713;d=Nb({node:f,path:Fb(f),flags:b,seekable:!0,position:0,cf:f.cf,Tg:[],error:!1},d);d.cf.open&&d.cf.open(d);!g.logReadFiles||b&1||(Wb||(Wb={}),a in Wb||(Wb[a]=1,h("FS.trackingDelegate error on read file: "+
a)));try{Cb.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),Cb.onOpenFile(a,f))}catch(k){h("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+k.message)}return d}function Xb(a){if(null===a.fd)throw new J(8);a.Yf&&(a.Yf=null);try{a.cf.close&&a.cf.close(a)}catch(b){throw b;}finally{yb[a.fd]=null}a.fd=null}
function Yb(a,b,c){if(null===a.fd)throw new J(8);if(!a.seekable||!a.cf.rf)throw new J(70);if(0!=c&&1!=c&&2!=c)throw new J(28);a.position=a.cf.rf(a,b,c);a.Tg=[]}
function Zb(a,b,c,d,e,f){if(0>d||0>e)throw new J(28);if(null===a.fd)throw new J(8);if(0===(a.flags&2097155))throw new J(8);if(16384===(a.node.mode&61440))throw new J(31);if(!a.cf.write)throw new J(28);a.seekable&&a.flags&1024&&Yb(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new J(70);b=a.cf.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&Cb.onWriteToFile)Cb.onWriteToFile(a.path)}catch(l){h("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+
l.message)}return b}function $b(){J||(J=function(a,b){this.node=b;this.Sg=function(c){this.kf=c};this.Sg(a);this.message="FS error"},J.prototype=Error(),J.prototype.constructor=J,[44].forEach(function(a){ub[a]=new J(a);ub[a].stack="<generic error, no stack>"}))}var ac;function bc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function cc(a,b){a="string"===typeof a?a:Fb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=gb(a+"/"+c);try{L(d)}catch(e){}a=d}}return d}
function dc(a,b,c,d){a=gb(("string"===typeof a?a:Fb(a))+"/"+b);c=bc(c,d);return Qb(a,(void 0!==c?c:438)&4095|32768,0)}function ec(a,b,c,d,e,f){a=b?gb(("string"===typeof a?a:Fb(a))+"/"+b):a;d=bc(d,e);e=Qb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Ub(e,d|146);a=Vb(e,577);Zb(a,c,0,c.length,0,f);Xb(a);Ub(e,d)}return e}
function M(a,b,c,d){a=gb(("string"===typeof a?a:Fb(a))+"/"+b);b=bc(!!c,!!d);M.mg||(M.mg=64);var e=M.mg++<<8|0;nb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,k,l,m){for(var r=0,t=0;t<m;t++){try{var u=c()}catch(w){throw new J(29);}if(void 0===u&&0===r)throw new J(6);if(null===u||void 0===u)break;r++;k[l+t]=u}r&&(f.node.timestamp=Date.now());return r},write:function(f,k,l,m){for(var r=0;r<m;r++)try{d(k[l+r])}catch(t){throw new J(29);}m&&(f.node.timestamp=
Date.now());return r}});return Rb(a,b,e)}function fc(a){if(!(a.Jg||a.Kg||a.link||a.bf)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ka)try{a.bf=pb(ka(a.url),!0),a.ef=a.bf.length}catch(b){throw new J(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function hc(a,b,c,d,e){function f(){this.Zf=!1;this.jf=[]}f.prototype.get=function(t){if(!(t>this.length-1||0>t)){var u=t%this.chunkSize;return this.lg(t/this.chunkSize|0)[u]}};f.prototype.Qf=function(t){this.lg=t};f.prototype.dg=function(){var t=new XMLHttpRequest;t.open("HEAD",c,!1);t.send(null);if(!(200<=t.status&&300>t.status||304===t.status))throw Error("Couldn't load "+c+". Status: "+t.status);var u=Number(t.getResponseHeader("Content-length")),w,y=(w=t.getResponseHeader("Accept-Ranges"))&&
"bytes"===w;t=(w=t.getResponseHeader("Content-Encoding"))&&"gzip"===w;var B=1048576;y||(B=u);var D=this;D.Qf(function(H){var db=H*B,Da=(H+1)*B-1;Da=Math.min(Da,u-1);if("undefined"===typeof D.jf[H]){var me=D.jf;if(db>Da)throw Error("invalid range ("+db+", "+Da+") or no bytes requested!");if(Da>u-1)throw Error("only "+u+" bytes available! programmer error!");var P=new XMLHttpRequest;P.open("GET",c,!1);u!==B&&P.setRequestHeader("Range","bytes="+db+"-"+Da);"undefined"!=typeof Uint8Array&&(P.responseType=
"arraybuffer");P.overrideMimeType&&P.overrideMimeType("text/plain; charset=x-user-defined");P.send(null);if(!(200<=P.status&&300>P.status||304===P.status))throw Error("Couldn't load "+c+". Status: "+P.status);db=void 0!==P.response?new Uint8Array(P.response||[]):pb(P.responseText||"",!0);me[H]=db}if("undefined"===typeof D.jf[H])throw Error("doXHR failed!");return D.jf[H]});if(t||!u)B=u=1,B=u=this.lg(0).length,qa("LazyFiles on gzip forces download of the whole file when length is accessed");this.zg=
u;this.yg=B;this.Zf=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.Zf||this.dg();return this.zg}},chunkSize:{get:function(){this.Zf||this.dg();return this.yg}}});var l=void 0}else l=c,k=void 0;var m=dc(a,b,d,e);k?m.bf=k:l&&(m.bf=null,m.url=l);Object.defineProperties(m,{ef:{get:function(){return this.bf.length}}});
var r={};Object.keys(m.cf).forEach(function(t){var u=m.cf[t];r[t]=function(){fc(m);return u.apply(null,arguments)}});r.read=function(t,u,w,y,B){fc(m);t=t.node.bf;if(B>=t.length)return 0;y=Math.min(t.length-B,y);if(t.slice)for(var D=0;D<y;D++)u[w+D]=t[B+D];else for(D=0;D<y;D++)u[w+D]=t.get(B+D);return y};m.cf=r;return m}
function ic(a,b,c,d,e,f,k,l,m,r){function t(y){function B(H){r&&r();l||ec(a,b,H,d,e,m);f&&f();Va(w)}var D=!1;g.preloadPlugins.forEach(function(H){!D&&H.canHandle(u)&&(H.handle(y,u,B,function(){k&&k();Va(w)}),D=!0)});D||B(y)}jc();var u=b?kb(gb(a+"/"+b)):a,w="cp "+u;Ua(w);"string"==typeof c?kc(c,function(y){t(y)},k):t(c)}var N={},Ob,Wb,lc={},mc=void 0;function nc(){mc+=4;return v[mc-4>>2]}function oc(a){a=yb[a];if(!a)throw new J(8);return a}var pc;
ia?pc=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?pc=dateNow:pc=function(){return performance.now()};var qc=[];function rc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,k){b.drawElementsInstancedANGLE(c,d,e,f,k)})}
function sc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function tc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
var uc=1,vc=[],O=[],wc=[],xc=[],yc=[],Q=[],zc=[],Ac=[],R=[],S=[],Bc=[],Cc=[],Dc={},Ec={},Fc=4;function T(a){Gc||(Gc=a)}function Hc(a){for(var b=uc++,c=a.length;c<b;c++)a[c]=null;return b}function Ic(a,b){a.jg||(a.jg=a.getContext,a.getContext=function(d,e){e=a.jg(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.ng?a.getContext("webgl2",b):a.getContext("webgl",b);return c?Jc(c,b):0}
function Jc(a,b){var c=Hc(Ac),d={eh:c,attributes:b,version:b.ng,Of:a};a.canvas&&(a.canvas.Wg=d);Ac[c]=d;("undefined"===typeof b.Eg||b.Eg)&&Kc(d);return c}
function Kc(a){a||(a=U);if(!a.Hg){a.Hg=!0;var b=a.Of;rc(b);sc(b);tc(b);b.$g=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.fh=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.gf=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.gf)b.gf=b.getExtension("EXT_disjoint_timer_query");b.ih=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var Lc={},Gc,U,Mc=[];function Nc(a,b,c,d){for(var e=0;e<a;e++){var f=V[c](),k=f&&Hc(d);f?(f.name=k,d[k]=f):T(1282);v[b+4*e>>2]=k}}function Oc(a,b,c,d,e,f,k,l){b=O[b];if(a=V[a](b,c))d=l&&E(a.name,A,l,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),k&&(v[k>>2]=a.type)}function Pc(a,b){F[a>>2]=b;F[a+4>>2]=(b-F[a>>2])/4294967296}
function Qc(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 34814:case 36345:d=0;break;case 34466:var e=V.getParameter(34467);d=e?e.length:0;break;case 33309:if(2>U.version){T(1282);return}d=2*(V.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>U.version){T(1280);return}d=33307==a?3:0}if(void 0===d)switch(e=V.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===
e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);
h("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);h("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Pc(b,d);break;case 0:v[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else T(1281)}
function Rc(a,b,c,d){if(c){b=V.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:T(1280);return}else if(b instanceof WebGLBuffer)a=b.name|0;else{T(1280);return}break;default:T(1280);return}switch(d){case 1:Pc(c,a);break;case 0:v[c>>2]=a;break;case 2:z[c>>2]=a;break;case 4:q[c>>0]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}}else T(1281)}
function Sc(a){var b=Ga(a)+1,c=Ca(b);E(a,A,c,b);return c}function Tc(a,b,c,d){if(c)if(a=O[a],a=V.getUniform(a,a.yf[b]),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else T(1281)}
function Uc(a,b,c,d){if(c)if(a=V.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:v[c+4*b>>2]=Math.fround(a[b])}else T(1281)}function Vc(a){a-=5120;return 0==a?q:1==a?A:2==a?va:4==a?v:6==a?z:5==a||28922==a||28520==a||30779==a||30782==a?F:Ka}
function Wc(a){return 31-Math.clz32(a.BYTES_PER_ELEMENT)}function Xc(a,b,c,d,e){a=Vc(a);var f=Wc(a),k=Fc;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<f)+k-1&-k)>>f)}function W(a){var b=V.Cg,c=b.yf[a];0<=c&&(b.yf[a]=c=V.getUniformLocation(b,b.vg[a]+(0<c?"["+c+"]":"")));return c}var Yc=[],Zc=[];
function $c(a){if(!za)try{a()}catch(b){if(!(b instanceof pa)&&"unwind"!==b)throw b&&"object"===typeof b&&b.stack&&h("exception thrown: "+[b,b.stack]),b;}}var ad=!1,bd=null,cd=0,dd=null,ed=0,fd=0,gd=0,hd=0,id=[],jd={},kd,ld,md,nd=!1,od=!1,pd=[];
function jc(){function a(){od=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!qd){qd=!0;try{rd=!0}catch(c){rd=!1,console.log("warning: no blob constructor, cannot create blobs with mimetypes")}sd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:rd?null:console.log("warning: no BlobBuilder");
td="undefined"!=typeof window?window.URL?window.URL:window.webkitURL:void 0;g.pg||"undefined"!==typeof td||(console.log("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.pg=!0);g.preloadPlugins.push({canHandle:function(c){return!g.pg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var k=null;if(rd)try{k=new Blob([c],{type:ud(d)}),k.size!==c.length&&(k=new Blob([(new Uint8Array(c)).buffer],{type:ud(d)}))}catch(r){ra("Blob constructor present but fails: "+
r+"; falling back to blob builder")}k||(k=new sd,k.append((new Uint8Array(c)).buffer),k=k.getBlob());var l=td.createObjectURL(k),m=new Image;m.onload=function(){assert(m.complete,"Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=m.width;r.height=m.height;r.getContext("2d").drawImage(m,0,0);g.preloadedImages[d]=r;td.revokeObjectURL(l);e&&e(c)};m.onerror=function(){console.log("Image "+l+" could not be decoded");f&&f()};m.src=l}});g.preloadPlugins.push({canHandle:function(c){return!g.jh&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function k(u){m||(m=!0,g.preloadedAudios[d]=u,e&&e(c))}function l(){m||(m=!0,g.preloadedAudios[d]=new Audio,f&&f())}var m=!1;if(rd){try{var r=new Blob([c],{type:ud(d)})}catch(u){return l()}r=td.createObjectURL(r);var t=new Audio;t.addEventListener("canplaythrough",function(){k(t)},!1);t.onerror=function(){if(!m){console.log("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var u="",w=0,y=0,
B=0;B<c.length;B++)for(w=w<<8|c[B],y+=8;6<=y;){var D=w>>y-6&63;y-=6;u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}2==y?(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&3)<<4],u+="=="):4==y&&(u+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(w&15)<<2],u+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+u;k(t)}};t.src=r;vd(function(){k(t)})}else return l()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&
b.addEventListener("click",function(c){!od&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function wd(a,b,c,d){if(b&&g.sf&&a==g.canvas)return g.sf;var e;if(b){var f={antialias:!1,alpha:!1,ng:"undefined"!==typeof WebGL2RenderingContext?2:1};if(d)for(var k in d)f[k]=d[k];if("undefined"!==typeof Lc&&(e=Ic(a,f)))var l=Ac[e].Of}else l=a.getContext("2d");if(!l)return null;c&&(b||assert("undefined"===typeof V,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.sf=l,b&&(U=Ac[e],g.sf=V=U&&U.Of),g.lh=b,pd.forEach(function(m){m()}),jc());return l}
var xd=!1,yd=void 0,zd=void 0;
function Ad(a,b){function c(){nd=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Bd,yd&&d.requestPointerLock(),nd=!0,zd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=F[SDL.screen>>2]|8388608),Cd(g.canvas),Dd()):Cd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),zd?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=F[SDL.screen>>2]&
-8388609),Cd(g.canvas),Dd()):Cd(d));if(g.onFullScreen)g.onFullScreen(nd);if(g.onFullscreen)g.onFullscreen(nd)}yd=a;zd=b;"undefined"===typeof yd&&(yd=!0);"undefined"===typeof zd&&(zd=!1);var d=g.canvas;xd||(xd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Bd(){if(!nd)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Ed=0;function Fd(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Ed)Ed=b+1E3/60;else for(;b+2>=Ed;)Ed+=1E3/60;setTimeout(a,Math.max(Ed-b,0))}}function vd(a){setTimeout(function(){$c(a)},1E4)}
function ud(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Gd=0,Hd=0,Id=0,Jd=0;
function Kd(a){if(od)"mousemove"!=a.type&&"mozMovementX"in a?Id=Jd=0:(Id=a.movementX||a.mozMovementX||a.webkitMovementX||0,Jd=a.movementY||a.mozMovementY||a.webkitMovementY||0),"undefined"!=typeof SDL?(Gd=SDL.gh+Id,Hd=SDL.hh+Jd):(Gd+=Id,Hd+=Jd);else{var b=g.canvas.getBoundingClientRect(),c=g.canvas.width,d=g.canvas.height,e="undefined"!==typeof window.scrollX?window.scrollX:window.pageXOffset,f="undefined"!==typeof window.scrollY?window.scrollY:window.pageYOffset;"touchstart"!==a.type&&"touchend"!==
a.type&&"touchmove"!==a.type&&(e=a.pageX-(e+b.left),a=a.pageY-(f+b.top),e*=c/b.width,a*=d/b.height,Id=e-Gd,Jd=a-Hd,Gd=e,Hd=a)}}function kc(a,b,c){var d="al "+a;la(a,function(e){assert(e,'Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&Va(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&Ua(d)}var Ld=[];function Dd(){var a=g.canvas;Ld.forEach(function(b){b(a.width,a.height)})}function Md(a,b,c){Cd(g.canvas,a,b);c||Dd()}
function Cd(a,b,c){b&&c?(a.Vg=b,a.Gg=c):(b=a.Vg,c=a.Gg);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}zd?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var qd,rd,sd,td;
function Nd(a,b){fd=a;gd=b;if(dd)if(ad||(ad=!0),0==a)bd=function(){var d=Math.max(0,ld+b-pc())|0;setTimeout(md,d)};else if(1==a)bd=function(){Fd(md)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ha?(void 0===g.setImmediates&&(g.setImmediates=[]),g.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}bd=function(){setImmediate(md)}}}
function Od(a,b,c,d,e){function f(){if(k<cd){if(!noExitRuntime)try{Pd(Aa)}catch(l){if(!(l instanceof pa))throw l;}return!1}return!0}assert(!dd,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");dd=a;ed=d;var k=cd;ad=!1;md=function(){if(!za)if(0<id.length){var l=Date.now(),m=id.shift();m.Fg(m.zf);if(kd){var r=kd,t=0==r%1?r-1:Math.floor(r);kd=m.Zg?t:(8*r+(t+.5))/
9}console.log('main loop blocker "'+m.name+'" took '+(Date.now()-l)+" ms");g.setStatus&&(l=g.statusMessage||"Please wait...",m=kd,r=jd.ah,m?m<r?g.setStatus(l+" ("+(r-m)+"/"+r+")"):g.setStatus(l):g.setStatus(""));f()&&setTimeout(md,0)}else f()&&(hd=hd+1|0,1==fd&&1<gd&&0!=hd%gd?bd():(0==fd&&(ld=pc()),za||g.preMainLoop&&!1===g.preMainLoop()||($c(a),g.postMainLoop&&g.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Qg&&SDL.audio.Qg(),bd())))};e||(b&&0<b?Nd(0,1E3/b):Nd(1,1),bd());if(c)throw"unwind";
}var Qd={};function Rd(){if(!Sd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in Qd)a[b]=Qd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Sd=c}return Sd}var Sd;
function Td(a,b,c,d){this.id=a;this.y=this.x=0;this.Xf=!1;this.ug=this.tg=0;this.width=b;this.height=c;this.sg=b;this.rg=c;this.title=d;this.attributes=Ud;this.buttons=0;this.keys=[];this.Tf=[];this.eg=this.Df=this.Uf=this.Mf=this.Af=this.Bf=this.Kf=this.Cf=this.wg=this.xg=this.title=null}function Vd(a){return 0>=a||!X?null:X[a-1]}
var Wd=null,Y=null,X=null,Ud=null,Xd={131073:0,131074:0,131075:1,131076:1,131077:1,135169:8,135170:8,135171:8,135172:8,135173:24,135174:8,135175:0,135176:0,135177:0,135178:0,135179:0,135180:0,135181:0,135182:0,135183:0,139265:196609,139266:1,139267:0,139268:0,139269:0,139270:0,139271:0,139272:0};
function Yd(a){switch(a){case 32:return 32;case 222:return 39;case 188:return 44;case 173:return 45;case 189:return 45;case 190:return 46;case 191:return 47;case 48:return 48;case 49:return 49;case 50:return 50;case 51:return 51;case 52:return 52;case 53:return 53;case 54:return 54;case 55:return 55;case 56:return 56;case 57:return 57;case 59:return 59;case 61:return 61;case 187:return 61;case 65:return 65;case 66:return 66;case 67:return 67;case 68:return 68;case 69:return 69;case 70:return 70;case 71:return 71;
case 72:return 72;case 73:return 73;case 74:return 74;case 75:return 75;case 76:return 76;case 77:return 77;case 78:return 78;case 79:return 79;case 80:return 80;case 81:return 81;case 82:return 82;case 83:return 83;case 84:return 84;case 85:return 85;case 86:return 86;case 87:return 87;case 88:return 88;case 89:return 89;case 90:return 90;case 219:return 91;case 220:return 92;case 221:return 93;case 192:return 94;case 27:return 256;case 13:return 257;case 9:return 258;case 8:return 259;case 45:return 260;
case 46:return 261;case 39:return 262;case 37:return 263;case 40:return 264;case 38:return 265;case 33:return 266;case 34:return 267;case 36:return 268;case 35:return 269;case 20:return 280;case 145:return 281;case 144:return 282;case 44:return 283;case 19:return 284;case 112:return 290;case 113:return 291;case 114:return 292;case 115:return 293;case 116:return 294;case 117:return 295;case 118:return 296;case 119:return 297;case 120:return 298;case 121:return 299;case 122:return 300;case 123:return 301;
case 124:return 302;case 125:return 303;case 126:return 304;case 127:return 305;case 128:return 306;case 129:return 307;case 130:return 308;case 131:return 309;case 132:return 310;case 133:return 311;case 134:return 312;case 135:return 313;case 136:return 314;case 96:return 320;case 97:return 321;case 98:return 322;case 99:return 323;case 100:return 324;case 101:return 325;case 102:return 326;case 103:return 327;case 104:return 328;case 105:return 329;case 110:return 330;case 111:return 331;case 106:return 332;
case 109:return 333;case 107:return 334;case 16:return 340;case 17:return 341;case 18:return 342;case 91:return 343;case 93:return 348;default:return-1}}function Zd(){var a=Y,b=0;a.keys[340]&&(b|=1);a.keys[341]&&(b|=2);a.keys[342]&&(b|=4);a.keys[343]&&(b|=8);return b}function $d(a){Y&&Y.eg&&!a.ctrlKey&&!a.metaKey&&(a=a.charCode,0==a||0<=a&&31>=a||G.get(Y.eg)(Y.id,a))}
function ae(a,b){if(Y){var c=Yd(a);if(-1!=c){var d=b&&Y.keys[c];Y.keys[c]=b;Y.Tf[a]=b;Y.Df&&(d&&(b=2),G.get(Y.Df)(Y.id,c,a,b,Zd()))}}}function be(){ce()}function de(){ce()}function ee(a){ae(a.keyCode,1);8!==a.keyCode&&9!==a.keyCode||a.preventDefault()}function fe(a){ae(a.keyCode,0)}function ge(){if(Y)for(var a=0;a<Y.Tf.length;++a)Y.Tf[a]&&ae(a,0)}function he(a){Y&&(Kd(a),a.target==g.canvas&&Y.Bf&&G.get(Y.Bf)(Y.id,Gd,Hd))}function ie(a){Y&&a.target==g.canvas&&Y.Af&&G.get(Y.Af)(Y.id,1)}
function je(a){Y&&a.target==g.canvas&&Y.Af&&G.get(Y.Af)(Y.id,0)}function ke(a,b){if(Y&&(Kd(a),a.target==g.canvas)){var c=a.button;0<c&&(c=1==c?2:1);if(1==b){Y.buttons|=1<<c;try{a.target.setCapture()}catch(d){}}else Y.buttons&=~(1<<c);Y.Kf&&G.get(Y.Kf)(Y.id,c,b,Zd())}}function le(a){Y&&ke(a,1)}function ne(a){Y&&ke(a,0)}
function oe(a){switch(a.type){case "DOMMouseScroll":break;case "mousewheel":break;case "wheel":switch(a.deltaMode){case 0:break;case 1:break;case 2:break;default:throw"unrecognized mouse wheel delta mode: "+a.deltaMode;}break;default:throw"unrecognized mouse wheel event: "+a.type;}if(Y&&Y.Mf&&a.target==g.canvas){if("mousewheel"==a.type){var b=a.wheelDeltaX;var c=a.wheelDeltaY}else b=a.deltaX,c=a.deltaY;G.get(Y.Mf)(Y.id,b,c);a.preventDefault()}}var pe={},qe=null,re=null;
function ce(){if(hd!==re||!hd){qe=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads:null;re=hd;for(var a=0;a<qe.length;++a){var b=qe[a];if(b){pe[a]||(console.log("glfw joystick connected:",a),pe[a]={id:Ba(pb(b.id)),Yg:b.buttons.length,Xg:b.axes.length,buttons:Ba(Array(b.buttons.length)),axes:Ba(Array(4*b.axes.length))});for(var c=pe[a],d=0;d<b.buttons.length;++d)ua(c.buttons+d,b.buttons[d].pressed,"i8");for(d=0;d<b.axes.length;++d)ua(c.axes+4*d,
b.axes[d],"float")}else pe[a]&&(console.log("glfw joystick disconnected",a),se(pe[a].id),se(pe[a].buttons),se(pe[a].axes),delete pe[a])}}}
function te(a){function b(l){var m="/.glfw_dropped_files/"+l.name.replace(/\//g,"_"),r=new FileReader;r.onloadend=function(u){if(2!=r.readyState)++f,console.log("failed to read dropped file: "+l.name+": "+r.error);else{var w=new Uint8Array(u.target.result);var y=y||{};y.flags=y.flags||577;u=Vb(m,y.flags,y.mode);if("string"===typeof w){var B=new Uint8Array(Ga(w)+1);w=E(w,B,0,B.length);Zb(u,B,0,w,void 0,y.Bg)}else if(ArrayBuffer.isView(w))Zb(u,w,0,w.byteLength,void 0,y.Bg);else throw Error("Unsupported data type");
Xb(u);if(++f===e){G.get(Y.Uf)(Y.id,e,c);for(y=0;y<d.length;++y)se(d[y]);se(c)}}};r.readAsArrayBuffer(l);var t=Ba(pb(m));d.push(t);ua(c+4*k,t,"i8*")}if(Y&&Y.Uf&&a.dataTransfer&&a.dataTransfer.files&&0!=a.dataTransfer.files.length){a.preventDefault();var c=Ba(Array(4*a.dataTransfer.files.length)),d=[],e=a.dataTransfer.files.length,f=0;cc("/",".glfw_dropped_files");for(var k=0;k<e;++k)b(a.dataTransfer.files[k]);return!1}}function ue(a){if(Y&&Y.Uf)return a.preventDefault(),!1}
function Ib(a,b,c,d){a||(a=this);this.parent=a;this.pf=a.pf;this.wf=null;this.id=zb++;this.name=b;this.mode=c;this.df={};this.cf={};this.rdev=d}Object.defineProperties(Ib.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Kg:{get:function(){return 16384===(this.mode&61440)}},Jg:{get:function(){return 8192===(this.mode&61440)}}});$b();
Ab=Array(4096);Pb(K,"/");L("/tmp");L("/home");L("/home/web_user");(function(){L("/dev");nb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});Rb("/dev/null",259);mb(1280,qb);mb(1536,rb);Rb("/dev/tty",1280);Rb("/dev/tty1",1536);var a=jb();M("/dev","random",a);M("/dev","urandom",a);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Pb({pf:function(){var b=tb(a,"fd",16895,73);b.df={lookup:function(c,d){var e=yb[+d];if(!e)throw new J(8);c={parent:null,pf:{og:"fake"},df:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();g.FS_createPath=cc;g.FS_createDataFile=ec;g.FS_createPreloadedFile=ic;g.FS_createLazyFile=hc;g.FS_createDevice=M;g.FS_unlink=Tb;for(var V,Z=0;32>Z;++Z)Mc.push(Array(Z));var ve=new Float32Array(288);
for(Z=0;288>Z;++Z)Yc[Z]=ve.subarray(0,Z+1);var we=new Int32Array(288);for(Z=0;288>Z;++Z)Zc[Z]=we.subarray(0,Z+1);g.requestFullscreen=function(a,b){Ad(a,b)};g.requestAnimationFrame=function(a){Fd(a)};g.setCanvasSize=function(a,b,c){Md(a,b,c)};g.pauseMainLoop=function(){bd=null;cd++};g.resumeMainLoop=function(){cd++;var a=fd,b=gd,c=dd;dd=null;Od(c,0,!1,ed,!0);Nd(a,b);bd()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};
g.createContext=function(a,b,c,d){return wd(a,b,c,d)};function pb(a,b){var c=Array(Ga(a)+1);a=E(a,c,0,c.length);b&&(c.length=a);return c}
var Ae={a:function(a,b,c,d){p("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",c,d?C(d):"unknown function"])},l:function(a,b,c){mc=c;try{var d=oc(a);switch(b){case 0:var e=nc();return 0>e?-28:Vb(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=nc(),d.flags|=e,0;case 12:return e=nc(),va[e+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return v[xe()>>2]=28,-1;default:return-28}}catch(f){return"undefined"!==typeof N&&f instanceof J||
p(f),-f.kf}},Ra:function(a,b,c){mc=c;try{var d=oc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var e=nc();return v[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=nc();if(!d.cf.Ig)throw new J(59);return d.cf.Ig(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:p("bad ioctl syscall "+b)}}catch(f){return"undefined"!==typeof N&&f instanceof J||p(f),
-f.kf}},Pa:function(a,b,c,d,e,f){try{a:{f<<=12;var k=!1;if(0!==(d&16)&&0!==a%16384)var l=-28;else{if(0!==(d&32)){var m=ye(16384,b);if(!m){l=-48;break a}ze(m,0,b);k=!0}else{var r=yb[e];if(!r){l=-8;break a}var t=f;if(0!==(c&2)&&0===(d&2)&&2!==(r.flags&2097155))throw new J(2);if(1===(r.flags&2097155))throw new J(2);if(!r.cf.Jf)throw new J(43);var u=r.cf.Jf(r,a,b,t,c,d);m=u.Pg;k=u.Pf}lc[m]={Mg:m,Lg:b,Pf:k,fd:e,Og:c,flags:d,offset:f};l=m}}return l}catch(w){return"undefined"!==typeof N&&w instanceof J||
p(w),-w.kf}},Oa:function(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=lc[a];if(d&&b===d.Lg){var e=yb[d.fd];if(e&&d.Og&2){var f=d.flags,k=d.offset,l=A.slice(a,a+b);e&&e.cf.Lf&&e.cf.Lf(e,l,k,b,f)}lc[a]=null;d.Pf&&se(d.Mg)}c=0}return c}catch(m){return"undefined"!==typeof N&&m instanceof J||p(m),-m.kf}},Ta:function(a,b,c){mc=c;try{var d=C(a),e=c?nc():0;return Vb(d,b,e).fd}catch(f){return"undefined"!==typeof N&&f instanceof J||p(f),-f.kf}},Ka:function(){p()},g:function(a,b){if(0===a)a=Date.now();
else if(1===a||4===a)a=pc();else return v[xe()>>2]=28,-1;v[b>>2]=a/1E3|0;v[b+4>>2]=a%1E3*1E6|0;return 0},b:function(a,b,c){qc.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,qc.push(d?xa[c++>>1]:v[c]),++c;return bb[a].apply(null,qc)},sa:function(a){V.activeTexture(a)},ra:function(a,b){V.attachShader(O[a],Q[b])},Jc:function(a,b){V.beginQuery(a,R[b])},ab:function(a,b){V.gf.beginQueryEXT(a,R[b])},pc:function(a){V.beginTransformFeedback(a)},qa:function(a,b,c){V.bindAttribLocation(O[a],b,C(c))},
pa:function(a,b){35051==a?V.Sf=b:35052==a&&(V.mf=b);V.bindBuffer(a,vc[b])},mc:function(a,b,c){V.bindBufferBase(a,b,vc[c])},nc:function(a,b,c,d,e){V.bindBufferRange(a,b,vc[c],d,e)},oa:function(a,b){V.bindFramebuffer(a,wc[b])},ma:function(a,b){V.bindRenderbuffer(a,xc[b])},sb:function(a,b){V.bindSampler(a,S[b])},la:function(a,b){V.bindTexture(a,yc[b])},jb:function(a,b){V.bindTransformFeedback(a,Bc[b])},uc:function(a){V.bindVertexArray(zc[a])},Ba:function(a){V.bindVertexArray(zc[a])},ka:function(a,b,
c,d){V.blendColor(a,b,c,d)},ja:function(a){V.blendEquation(a)},ia:function(a,b){V.blendEquationSeparate(a,b)},ha:function(a,b){V.blendFunc(a,b)},ga:function(a,b,c,d){V.blendFuncSeparate(a,b,c,d)},xc:function(a,b,c,d,e,f,k,l,m,r){V.blitFramebuffer(a,b,c,d,e,f,k,l,m,r)},fa:function(a,b,c,d){2<=U.version?c?V.bufferData(a,A,d,c,b):V.bufferData(a,b,d):V.bufferData(a,c?A.subarray(c,c+b):b,d)},ea:function(a,b,c,d){2<=U.version?V.bufferSubData(a,b,A,d,c):V.bufferSubData(a,b,A.subarray(d,d+c))},da:function(a){return V.checkFramebufferStatus(a)},
ba:function(a){V.clear(a)},Rb:function(a,b,c,d){V.clearBufferfi(a,b,c,d)},Sb:function(a,b,c){V.clearBufferfv(a,b,z,c>>2)},Ub:function(a,b,c){V.clearBufferiv(a,b,v,c>>2)},Tb:function(a,b,c){V.clearBufferuiv(a,b,F,c>>2)},aa:function(a,b,c,d){V.clearColor(a,b,c,d)},$:function(a){V.clearDepth(a)},_:function(a){V.clearStencil(a)},Cb:function(a,b,c,d){return V.clientWaitSync(Cc[a],b,(c>>>0)+4294967296*d)},Z:function(a,b,c,d){V.colorMask(!!a,!!b,!!c,!!d)},Y:function(a){V.compileShader(Q[a])},X:function(a,
b,c,d,e,f,k,l){2<=U.version?V.mf?V.compressedTexImage2D(a,b,c,d,e,f,k,l):V.compressedTexImage2D(a,b,c,d,e,f,A,l,k):V.compressedTexImage2D(a,b,c,d,e,f,l?A.subarray(l,l+k):null)},Oc:function(a,b,c,d,e,f,k,l,m){V.mf?V.compressedTexImage3D(a,b,c,d,e,f,k,l,m):V.compressedTexImage3D(a,b,c,d,e,f,k,A,m,l)},W:function(a,b,c,d,e,f,k,l,m){2<=U.version?V.mf?V.compressedTexSubImage2D(a,b,c,d,e,f,k,l,m):V.compressedTexSubImage2D(a,b,c,d,e,f,k,A,m,l):V.compressedTexSubImage2D(a,b,c,d,e,f,k,m?A.subarray(m,m+l):null)},
Nc:function(a,b,c,d,e,f,k,l,m,r,t){V.mf?V.compressedTexSubImage3D(a,b,c,d,e,f,k,l,m,r,t):V.compressedTexSubImage3D(a,b,c,d,e,f,k,l,m,A,t,r)},Pb:function(a,b,c,d,e){V.copyBufferSubData(a,b,c,d,e)},V:function(a,b,c,d,e,f,k,l){V.copyTexImage2D(a,b,c,d,e,f,k,l)},U:function(a,b,c,d,e,f,k,l){V.copyTexSubImage2D(a,b,c,d,e,f,k,l)},Qc:function(a,b,c,d,e,f,k,l,m){V.copyTexSubImage3D(a,b,c,d,e,f,k,l,m)},S:function(){var a=Hc(O),b=V.createProgram();b.name=a;b.Gf=b.Ef=b.Ff=0;b.bg=1;O[a]=b;return a},R:function(a){var b=
Hc(Q);Q[b]=V.createShader(a);return b},Q:function(a){V.cullFace(a)},P:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=vc[d];e&&(V.deleteBuffer(e),e.name=0,vc[d]=null,d==V.Sf&&(V.Sf=0),d==V.mf&&(V.mf=0))}},O:function(a,b){for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=wc[d];e&&(V.deleteFramebuffer(e),e.name=0,wc[d]=null)}},N:function(a){if(a){var b=O[a];b?(V.deleteProgram(b),b.name=0,O[a]=null):T(1281)}},Lc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(V.deleteQuery(e),R[d]=null)}},
wb:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=R[d];e&&(V.gf.deleteQueryEXT(e),R[d]=null)}},M:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=xc[d];e&&(V.deleteRenderbuffer(e),e.name=0,xc[d]=null)}},ub:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(V.deleteSampler(e),e.name=0,S[d]=null)}},L:function(a){if(a){var b=Q[a];b?(V.deleteShader(b),Q[a]=null):T(1281)}},Db:function(a){if(a){var b=Cc[a];b?(V.deleteSync(b),b.name=0,Cc[a]=null):T(1281)}},K:function(a,b){for(var c=
0;c<a;c++){var d=v[b+4*c>>2],e=yc[d];e&&(V.deleteTexture(e),e.name=0,yc[d]=null)}},ib:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Bc[d];e&&(V.deleteTransformFeedback(e),e.name=0,Bc[d]=null)}},tc:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];V.deleteVertexArray(zc[d]);zc[d]=null}},Aa:function(a,b){for(var c=0;c<a;c++){var d=v[b+4*c>>2];V.deleteVertexArray(zc[d]);zc[d]=null}},J:function(a){V.depthFunc(a)},H:function(a){V.depthMask(!!a)},G:function(a,b){V.depthRange(a,b)},F:function(a,
b){V.detachShader(O[a],Q[b])},E:function(a){V.disable(a)},D:function(a){V.disableVertexAttribArray(a)},C:function(a,b,c){V.drawArrays(a,b,c)},Ib:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},va:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Zc:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},$c:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Va:function(a,b,c,d){V.drawArraysInstanced(a,b,c,d)},Fc:function(a,b){for(var c=Mc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];V.drawBuffers(c)},Vc:function(a,
b){for(var c=Mc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];V.drawBuffers(c)},wa:function(a,b){for(var c=Mc[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];V.drawBuffers(c)},B:function(a,b,c,d){V.drawElements(a,b,c,d)},Gb:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},ua:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Wc:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Xc:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Yc:function(a,b,c,d,e){V.drawElementsInstanced(a,b,c,d,e)},Tc:function(a,b,
c,d,e,f){V.drawElements(a,d,e,f)},A:function(a){V.enable(a)},z:function(a){V.enableVertexAttribArray(a)},Ic:function(a){V.endQuery(a)},Sa:function(a){V.gf.endQueryEXT(a)},oc:function(){V.endTransformFeedback()},Fb:function(a,b){return(a=V.fenceSync(a,b))?(b=Hc(Cc),a.name=b,Cc[b]=a,b):0},y:function(){V.finish()},w:function(){V.flush()},v:function(a,b,c,d){V.framebufferRenderbuffer(a,b,c,xc[d])},u:function(a,b,c,d,e){V.framebufferTexture2D(a,b,c,yc[d],e)},vc:function(a,b,c,d,e){V.framebufferTextureLayer(a,
b,yc[c],d,e)},t:function(a){V.frontFace(a)},s:function(a,b){Nc(a,b,"createBuffer",vc)},q:function(a,b){Nc(a,b,"createFramebuffer",wc)},Mc:function(a,b){Nc(a,b,"createQuery",R)},Hb:function(a,b){for(var c=0;c<a;c++){var d=V.gf.createQueryEXT();if(!d){for(T(1282);c<a;)v[b+4*c++>>2]=0;break}var e=Hc(R);d.name=e;R[e]=d;v[b+4*c>>2]=e}},p:function(a,b){Nc(a,b,"createRenderbuffer",xc)},vb:function(a,b){Nc(a,b,"createSampler",S)},o:function(a,b){Nc(a,b,"createTexture",yc)},hb:function(a,b){Nc(a,b,"createTransformFeedback",
Bc)},sc:function(a,b){Nc(a,b,"createVertexArray",zc)},za:function(a,b){Nc(a,b,"createVertexArray",zc)},r:function(a){V.generateMipmap(a)},n:function(a,b,c,d,e,f,k){Oc("getActiveAttrib",a,b,c,d,e,f,k)},Qe:function(a,b,c,d,e,f,k){Oc("getActiveUniform",a,b,c,d,e,f,k)},Kb:function(a,b,c,d,e){a=O[a];if(a=V.getActiveUniformBlockName(a,b))e&&0<c?(c=E(a,A,e,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0)},Lb:function(a,b,c,d){if(d)if(a=O[a],35393==c)c=V.getActiveUniformBlockName(a,b),v[d>>2]=c.length+1;else{if(a=V.getActiveUniformBlockParameter(a,
b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)v[d+4*c>>2]=a[c];else v[d>>2]=a}else T(1281)},Nb:function(a,b,c,d,e){if(e)if(0<b&&0==c)T(1281);else{a=O[a];for(var f=[],k=0;k<b;k++)f.push(v[c+4*k>>2]);if(a=V.getActiveUniforms(a,f,d))for(b=a.length,k=0;k<b;k++)v[e+4*k>>2]=a[k]}else T(1281)},Pe:function(a,b,c,d){a=V.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=Q.indexOf(a[b])},Oe:function(a,b){return V.getAttribLocation(O[a],C(b))},Ne:function(a,b){Qc(a,b,
4)},xb:function(a,b,c){c?Pc(c,V.getBufferParameter(a,b)):T(1281)},Me:function(a,b,c){c?v[c>>2]=V.getBufferParameter(a,b):T(1281)},Le:function(){var a=V.getError()||Gc;Gc=0;return a},Ke:function(a,b){Qc(a,b,2)},bc:function(a,b){return V.getFragDataLocation(O[a],C(b))},Je:function(a,b,c,d){a=V.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},yb:function(a,b,c){Rc(a,b,c,1)},Ab:function(a,b){Qc(a,b,1)},qc:function(a,b,c){Rc(a,
b,c,0)},Ie:function(a,b){Qc(a,b,0)},Xa:function(a,b,c,d,e){if(0>d)T(1281);else if(e){if(a=V.getInternalformatParameter(a,b,c),null!==a)for(b=0;b<a.length&&b<d;++b)v[e+b>>2]=a[b]}else T(1281)},db:function(){T(1282)},Fe:function(a,b,c,d){a=V.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,A,d,b):0;c&&(v[c>>2]=b)},He:function(a,b,c){if(c)if(a>=uc)T(1281);else if(a=O[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Gf)for(b=
0;b<V.getProgramParameter(a,35718);++b)a.Gf=Math.max(a.Gf,V.getActiveUniform(a,b).name.length+1);v[c>>2]=a.Gf}else if(35722==b){if(!a.Ef)for(b=0;b<V.getProgramParameter(a,35721);++b)a.Ef=Math.max(a.Ef,V.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.Ef}else if(35381==b){if(!a.Ff)for(b=0;b<V.getProgramParameter(a,35382);++b)a.Ff=Math.max(a.Ff,V.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Ff}else v[c>>2]=V.getProgramParameter(a,b);else T(1281)},Da:function(a,b,c){if(c){a=R[a];b=2>U.version?V.gf.getQueryObjectEXT(a,
b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Pc(c,d)}else T(1281)},Fa:function(a,b,c){if(c){a=V.gf.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},Ca:function(a,b,c){if(c){a=R[a];b=2>U.version?V.gf.getQueryObjectEXT(a,b):V.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Pc(c,d)}else T(1281)},Gc:function(a,b,c){if(c){a=V.getQueryParameter(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},Ea:function(a,b,c){if(c){a=
V.gf.getQueryObjectEXT(R[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else T(1281)},Hc:function(a,b,c){c?v[c>>2]=V.getQuery(a,b):T(1281)},Ga:function(a,b,c){c?v[c>>2]=V.gf.getQueryEXT(a,b):T(1281)},Ee:function(a,b,c){c?v[c>>2]=V.getRenderbufferParameter(a,b):T(1281)},mb:function(a,b,c){c?z[c>>2]=V.getSamplerParameter(S[a],b):T(1281)},nb:function(a,b,c){c?v[c>>2]=V.getSamplerParameter(S[a],b):T(1281)},Ce:function(a,b,c,d){a=V.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?
E(a,A,d,b):0;c&&(v[c>>2]=b)},Be:function(a,b,c,d){a=V.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},Ae:function(a,b,c,d){if(a=V.getShaderSource(Q[a]))b=0<b&&d?E(a,A,d,b):0,c&&(v[c>>2]=b)},De:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(Q[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(Q[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=V.getShaderParameter(Q[a],b):T(1281)},ze:function(a){var b=Dc[a];if(!b){switch(a){case 7939:b=
V.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Sc(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||T(1280);b=b&&Sc(b);break;case 7938:b=V.getParameter(7938);b=2<=U.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=Sc(b);break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Sc(b);break;default:T(1280)}Dc[a]=
b}return b},Qb:function(a,b){if(2>U.version)return T(1282),0;var c=Ec[a];if(c)return 0>b||b>=c.length?(T(1281),0):c[b];switch(a){case 7939:return c=V.getSupportedExtensions()||[],c=c.concat(c.map(function(d){return"GL_"+d})),c=c.map(function(d){return Sc(d)}),c=Ec[a]=c,0>b||b>=c.length?(T(1281),0):c[b];default:return T(1280),0}},zb:function(a,b,c,d,e){0>c?T(1281):e?(a=V.getSyncParameter(Cc[a],b),null!==a&&(v[e>>2]=a,d&&(v[d>>2]=1))):T(1281)},ye:function(a,b,c){c?z[c>>2]=V.getTexParameter(a,b):T(1281)},
xe:function(a,b,c){c?v[c>>2]=V.getTexParameter(a,b):T(1281)},kc:function(a,b,c,d,e,f,k){a=O[a];if(a=V.getTransformFeedbackVarying(a,b))k&&0<c?(c=E(a.name,A,k,c),d&&(v[d>>2]=c)):d&&(v[d>>2]=0),e&&(v[e>>2]=a.size),f&&(v[f>>2]=a.type)},Mb:function(a,b){return V.getUniformBlockIndex(O[a],C(b))},Ob:function(a,b,c,d){if(d)if(0<b&&(0==c||0==d))T(1281);else{a=O[a];for(var e=[],f=0;f<b;f++)e.push(C(v[c+4*f>>2]));if(a=V.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)v[d+4*f>>2]=a[f]}else T(1281)},te:function(a,
b){function c(y){return"]"==y.slice(-1)&&y.lastIndexOf("[")}b=C(b);a=O[a];var d=a.yf,e=a.Ug,f,k=0,l=b,m=c(b);if(!d)for(a.yf=d={},a.vg={},f=0;f<V.getProgramParameter(a,35718);++f){var r=V.getActiveUniform(a,f);var t=r.name;r=r.size;var u=c(t);u=0<u?t.slice(0,u):t;var w=a.bg;a.bg+=r;e[u]=[r,w];for(t=0;t<r;++t)d[w]=t,a.vg[w++]=u}0<m&&(k=parseInt(b.slice(m+1))>>>0,l=b.slice(0,m));return(e=e[l])&&k<e[0]&&(k+=e[1],d[k]=d[k]||V.getUniformLocation(a,b))?k:-1},we:function(a,b,c){Tc(a,b,c,2)},ue:function(a,
b,c){Tc(a,b,c,0)},cc:function(a,b,c){Tc(a,b,c,0)},ic:function(a,b,c){Uc(a,b,c,0)},hc:function(a,b,c){Uc(a,b,c,0)},qe:function(a,b,c){c?v[c>>2]=V.getVertexAttribOffset(a,b):T(1281)},se:function(a,b,c){Uc(a,b,c,2)},re:function(a,b,c){Uc(a,b,c,5)},pe:function(a,b){V.hint(a,b)},$a:function(a,b,c){for(var d=Mc[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];V.invalidateFramebuffer(a,d)},_a:function(a,b,c,d,e,f,k){for(var l=Mc[b],m=0;m<b;m++)l[m]=v[c+4*m>>2];V.invalidateSubFramebuffer(a,l,d,e,f,k)},oe:function(a){return(a=
vc[a])?V.isBuffer(a):0},ne:function(a){return V.isEnabled(a)},me:function(a){return(a=wc[a])?V.isFramebuffer(a):0},le:function(a){return(a=O[a])?V.isProgram(a):0},Kc:function(a){return(a=R[a])?V.isQuery(a):0},lb:function(a){return(a=R[a])?V.gf.isQueryEXT(a):0},je:function(a){return(a=xc[a])?V.isRenderbuffer(a):0},tb:function(a){return(a=S[a])?V.isSampler(a):0},ie:function(a){return(a=Q[a])?V.isShader(a):0},Eb:function(a){return V.isSync(Cc[a])},he:function(a){return(a=yc[a])?V.isTexture(a):0},gb:function(a){return V.isTransformFeedback(Bc[a])},
rc:function(a){return(a=zc[a])?V.isVertexArray(a):0},xa:function(a){return(a=zc[a])?V.isVertexArray(a):0},ge:function(a){V.lineWidth(a)},fe:function(a){a=O[a];V.linkProgram(a);a.yf=0;a.Ug={}},fb:function(){V.pauseTransformFeedback()},ee:function(a,b){3317==a&&(Fc=b);V.pixelStorei(a,b)},de:function(a,b){V.polygonOffset(a,b)},cb:function(){T(1280)},bb:function(){T(1280)},Ja:function(a,b){V.gf.queryCounterEXT(R[a],b)},Uc:function(a){V.readBuffer(a)},ce:function(a,b,c,d,e,f,k){if(2<=U.version)if(V.Sf)V.readPixels(a,
b,c,d,e,f,k);else{var l=Vc(f);V.readPixels(a,b,c,d,e,f,l,k>>Wc(l))}else(k=Xc(f,e,c,d,k))?V.readPixels(a,b,c,d,e,f,k):T(1280)},be:function(){},ae:function(a,b,c,d){V.renderbufferStorage(a,b,c,d)},wc:function(a,b,c,d,e){V.renderbufferStorageMultisample(a,b,c,d,e)},eb:function(){V.resumeTransformFeedback()},_d:function(a,b){V.sampleCoverage(a,!!b)},pb:function(a,b,c){V.samplerParameterf(S[a],b,c)},ob:function(a,b,c){V.samplerParameterf(S[a],b,z[c>>2])},rb:function(a,b,c){V.samplerParameteri(S[a],b,c)},
qb:function(a,b,c){V.samplerParameteri(S[a],b,v[c>>2])},Zd:function(a,b,c,d){V.scissor(a,b,c,d)},Yd:function(){T(1280)},Xd:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?v[d+4*f>>2]:-1;e+=C(v[c+4*f>>2],0>k?void 0:k)}V.shaderSource(Q[a],e)},Wd:function(a,b,c){V.stencilFunc(a,b,c)},Vd:function(a,b,c,d){V.stencilFuncSeparate(a,b,c,d)},Ud:function(a){V.stencilMask(a)},Td:function(a,b){V.stencilMaskSeparate(a,b)},Sd:function(a,b,c){V.stencilOp(a,b,c)},Rd:function(a,b,c,d){V.stencilOpSeparate(a,b,
c,d)},Pd:function(a,b,c,d,e,f,k,l,m){if(2<=U.version)if(V.mf)V.texImage2D(a,b,c,d,e,f,k,l,m);else if(m){var r=Vc(l);V.texImage2D(a,b,c,d,e,f,k,l,r,m>>Wc(r))}else V.texImage2D(a,b,c,d,e,f,k,l,null);else V.texImage2D(a,b,c,d,e,f,k,l,m?Xc(l,k,d,e,m):null)},Sc:function(a,b,c,d,e,f,k,l,m,r){if(V.mf)V.texImage3D(a,b,c,d,e,f,k,l,m,r);else if(r){var t=Vc(m);V.texImage3D(a,b,c,d,e,f,k,l,m,t,r>>Wc(t))}else V.texImage3D(a,b,c,d,e,f,k,l,m,null)},Od:function(a,b,c){V.texParameterf(a,b,c)},Nd:function(a,b,c){V.texParameterf(a,
b,z[c>>2])},Md:function(a,b,c){V.texParameteri(a,b,c)},Ld:function(a,b,c){V.texParameteri(a,b,v[c>>2])},Za:function(a,b,c,d,e){V.texStorage2D(a,b,c,d,e)},Ya:function(a,b,c,d,e,f){V.texStorage3D(a,b,c,d,e,f)},Kd:function(a,b,c,d,e,f,k,l,m){if(2<=U.version)if(V.mf)V.texSubImage2D(a,b,c,d,e,f,k,l,m);else if(m){var r=Vc(l);V.texSubImage2D(a,b,c,d,e,f,k,l,r,m>>Wc(r))}else V.texSubImage2D(a,b,c,d,e,f,k,l,null);else r=null,m&&(r=Xc(l,k,e,f,m)),V.texSubImage2D(a,b,c,d,e,f,k,l,r)},Rc:function(a,b,c,d,e,f,
k,l,m,r,t){if(V.mf)V.texSubImage3D(a,b,c,d,e,f,k,l,m,r,t);else if(t){var u=Vc(r);V.texSubImage3D(a,b,c,d,e,f,k,l,m,r,u,t>>Wc(u))}else V.texSubImage3D(a,b,c,d,e,f,k,l,m,r,null)},lc:function(a,b,c,d){a=O[a];for(var e=[],f=0;f<b;f++)e.push(C(v[c+4*f>>2]));V.transformFeedbackVaryings(a,e,d)},Jd:function(a,b){V.uniform1f(W(a),b)},Id:function(a,b,c){if(2<=U.version)V.uniform1fv(W(a),z,c>>2,b);else{if(288>=b)for(var d=Yc[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);V.uniform1fv(W(a),
d)}},Hd:function(a,b){V.uniform1i(W(a),b)},Gd:function(a,b,c){if(2<=U.version)V.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Zc[b-1],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);V.uniform1iv(W(a),d)}},ac:function(a,b){V.uniform1ui(W(a),b)},Yb:function(a,b,c){V.uniform1uiv(W(a),F,c>>2,b)},Ed:function(a,b,c){V.uniform2f(W(a),b,c)},Dd:function(a,b,c){if(2<=U.version)V.uniform2fv(W(a),z,c>>2,2*b);else{if(144>=b)for(var d=Yc[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+
4)>>2];else d=z.subarray(c>>2,c+8*b>>2);V.uniform2fv(W(a),d)}},Cd:function(a,b,c){V.uniform2i(W(a),b,c)},Bd:function(a,b,c){if(2<=U.version)V.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b)for(var d=Zc[2*b-1],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);V.uniform2iv(W(a),d)}},$b:function(a,b,c){V.uniform2ui(W(a),b,c)},Xb:function(a,b,c){V.uniform2uiv(W(a),F,c>>2,2*b)},Ad:function(a,b,c,d){V.uniform3f(W(a),b,c,d)},zd:function(a,b,c){if(2<=U.version)V.uniform3fv(W(a),
z,c>>2,3*b);else{if(96>=b)for(var d=Yc[3*b-1],e=0;e<3*b;e+=3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);V.uniform3fv(W(a),d)}},yd:function(a,b,c,d){V.uniform3i(W(a),b,c,d)},xd:function(a,b,c){if(2<=U.version)V.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b)for(var d=Zc[3*b-1],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);V.uniform3iv(W(a),d)}},_b:function(a,b,c,d){V.uniform3ui(W(a),b,
c,d)},Wb:function(a,b,c){V.uniform3uiv(W(a),F,c>>2,3*b)},wd:function(a,b,c,d,e){V.uniform4f(W(a),b,c,d,e)},vd:function(a,b,c){if(2<=U.version)V.uniform4fv(W(a),z,c>>2,4*b);else{if(72>=b){var d=Yc[4*b-1],e=z;c>>=2;for(var f=0;f<4*b;f+=4){var k=c+f;d[f]=e[k];d[f+1]=e[k+1];d[f+2]=e[k+2];d[f+3]=e[k+3]}}else d=z.subarray(c>>2,c+16*b>>2);V.uniform4fv(W(a),d)}},td:function(a,b,c,d,e){V.uniform4i(W(a),b,c,d,e)},sd:function(a,b,c){if(2<=U.version)V.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b)for(var d=Zc[4*
b-1],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];else d=v.subarray(c>>2,c+16*b>>2);V.uniform4iv(W(a),d)}},Zb:function(a,b,c,d,e){V.uniform4ui(W(a),b,c,d,e)},Vb:function(a,b,c){V.uniform4uiv(W(a),F,c>>2,4*b)},Jb:function(a,b,c){a=O[a];V.uniformBlockBinding(a,b,c)},rd:function(a,b,c,d){if(2<=U.version)V.uniformMatrix2fv(W(a),!!c,z,d>>2,4*b);else{if(72>=b)for(var e=Yc[4*b-1],f=0;f<4*b;f+=4)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*
f+8)>>2],e[f+3]=z[d+(4*f+12)>>2];else e=z.subarray(d>>2,d+16*b>>2);V.uniformMatrix2fv(W(a),!!c,e)}},Dc:function(a,b,c,d){V.uniformMatrix2x3fv(W(a),!!c,z,d>>2,6*b)},Bc:function(a,b,c,d){V.uniformMatrix2x4fv(W(a),!!c,z,d>>2,8*b)},qd:function(a,b,c,d){if(2<=U.version)V.uniformMatrix3fv(W(a),!!c,z,d>>2,9*b);else{if(32>=b)for(var e=Yc[9*b-1],f=0;f<9*b;f+=9)e[f]=z[d+4*f>>2],e[f+1]=z[d+(4*f+4)>>2],e[f+2]=z[d+(4*f+8)>>2],e[f+3]=z[d+(4*f+12)>>2],e[f+4]=z[d+(4*f+16)>>2],e[f+5]=z[d+(4*f+20)>>2],e[f+6]=z[d+(4*
f+24)>>2],e[f+7]=z[d+(4*f+28)>>2],e[f+8]=z[d+(4*f+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);V.uniformMatrix3fv(W(a),!!c,e)}},Cc:function(a,b,c,d){V.uniformMatrix3x2fv(W(a),!!c,z,d>>2,6*b)},zc:function(a,b,c,d){V.uniformMatrix3x4fv(W(a),!!c,z,d>>2,12*b)},pd:function(a,b,c,d){if(2<=U.version)V.uniformMatrix4fv(W(a),!!c,z,d>>2,16*b);else{if(18>=b){var e=Yc[16*b-1],f=z;d>>=2;for(var k=0;k<16*b;k+=16){var l=d+k;e[k]=f[l];e[k+1]=f[l+1];e[k+2]=f[l+2];e[k+3]=f[l+3];e[k+4]=f[l+4];e[k+5]=f[l+5];e[k+6]=f[l+
6];e[k+7]=f[l+7];e[k+8]=f[l+8];e[k+9]=f[l+9];e[k+10]=f[l+10];e[k+11]=f[l+11];e[k+12]=f[l+12];e[k+13]=f[l+13];e[k+14]=f[l+14];e[k+15]=f[l+15]}}else e=z.subarray(d>>2,d+64*b>>2);V.uniformMatrix4fv(W(a),!!c,e)}},Ac:function(a,b,c,d){V.uniformMatrix4x2fv(W(a),!!c,z,d>>2,8*b)},yc:function(a,b,c,d){V.uniformMatrix4x3fv(W(a),!!c,z,d>>2,12*b)},od:function(a){a=O[a];V.useProgram(a);V.Cg=a},nd:function(a){V.validateProgram(O[a])},md:function(a,b){V.vertexAttrib1f(a,b)},ld:function(a,b){V.vertexAttrib1f(a,z[b>>
2])},kd:function(a,b,c){V.vertexAttrib2f(a,b,c)},id:function(a,b){V.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},hd:function(a,b,c,d){V.vertexAttrib3f(a,b,c,d)},gd:function(a,b){V.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},fd:function(a,b,c,d,e){V.vertexAttrib4f(a,b,c,d,e)},ed:function(a,b){V.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},kb:function(a,b){V.vertexAttribDivisor(a,b)},ta:function(a,b){V.vertexAttribDivisor(a,b)},ad:function(a,b){V.vertexAttribDivisor(a,b)},bd:function(a,b){V.vertexAttribDivisor(a,
b)},Wa:function(a,b){V.vertexAttribDivisor(a,b)},gc:function(a,b,c,d,e){V.vertexAttribI4i(a,b,c,d,e)},ec:function(a,b){V.vertexAttribI4i(a,v[b>>2],v[b+4>>2],v[b+8>>2],v[b+12>>2])},fc:function(a,b,c,d,e){V.vertexAttribI4ui(a,b,c,d,e)},dc:function(a,b){V.vertexAttribI4ui(a,F[b>>2],F[b+4>>2],F[b+8>>2],F[b+12>>2])},jc:function(a,b,c,d,e){V.vertexAttribIPointer(a,b,c,d,e)},dd:function(a,b,c,d,e,f){V.vertexAttribPointer(a,b,c,!!d,e,f)},cd:function(a,b,c,d){V.viewport(a,b,c,d)},Bb:function(a,b,c,d){V.waitSync(Cc[a],
b,(c>>>0)+4294967296*d)},d:function(){return 0},Ia:function(a,b,c){A.copyWithin(a,b,b+c)},h:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{ya.grow(Math.min(2147483648,d)-Ja.byteLength+65535>>>16);La();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ya:function(a,b,c){a=G.get(a);Od(a,b,c)},c:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";
},Na:function(a){for(var b=pc();pc()-b<a;);},La:function(a,b){try{var c=0;Rd().forEach(function(d,e){var f=b+c;e=v[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);q[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof N&&d instanceof J||p(d),d.kf}},Ma:function(a,b){try{var c=Rd();v[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});v[b>>2]=d;return 0}catch(e){return"undefined"!==typeof N&&e instanceof J||p(e),e.kf}},j:function(a){Pd(a)},m:function(a){try{var b=
oc(a);Xb(b);return 0}catch(c){return"undefined"!==typeof N&&c instanceof J||p(c),c.kf}},Qa:function(a,b,c,d){try{a:{for(var e=oc(a),f=a=0;f<c;f++){var k=v[b+(8*f+4)>>2],l=e,m=v[b+8*f>>2],r=k,t=void 0,u=q;if(0>r||0>t)throw new J(28);if(null===l.fd)throw new J(8);if(1===(l.flags&2097155))throw new J(8);if(16384===(l.node.mode&61440))throw new J(31);if(!l.cf.read)throw new J(28);var w="undefined"!==typeof t;if(!w)t=l.position;else if(!l.seekable)throw new J(70);var y=l.cf.read(l,u,m,r,t);w||(l.position+=
y);var B=y;if(0>B){var D=-1;break a}a+=B;if(B<k)break}D=a}v[d>>2]=D;return 0}catch(H){return"undefined"!==typeof N&&H instanceof J||p(H),H.kf}},Ha:function(a,b,c,d,e){try{var f=oc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Yb(f,a,d);wa=[f.position>>>0,(x=f.position,1<=+Math.abs(x)?0<x?(Math.min(+Math.floor(x/4294967296),4294967295)|0)>>>0:~~+Math.ceil((x-+(~~x>>>0))/4294967296)>>>0:0)];v[e>>2]=wa[0];v[e+4>>2]=wa[1];f.Yf&&0===a&&0===d&&(f.Yf=null);return 0}catch(k){return"undefined"!==
typeof N&&k instanceof J||p(k),k.kf}},Ua:function(a,b,c,d){try{a:{for(var e=oc(a),f=a=0;f<c;f++){var k=Zb(e,q,v[b+8*f>>2],v[b+(8*f+4)>>2],void 0);if(0>k){var l=-1;break a}a+=k}l=a}v[d>>2]=l;return 0}catch(m){return"undefined"!==typeof N&&m instanceof J||p(m),m.kf}},i:function(a){var b=Date.now();v[a>>2]=b/1E3|0;v[a+4>>2]=b%1E3*1E3|0;return 0},Ge:function(a,b,c,d){var e;for(e=0;e<X.length&&null!==X[e];e++);if(0<e)throw"glfwCreateWindow only supports one window at time currently";var f=e+1;if(0>=a||
0>=b)f=0;else{d?Ad():Md(a,b);for(e=0;e<X.length&&null==X[e];e++);d=0<Ud[139265];e==X.length&&(d?g.sf=wd(g.canvas,!0,!0,{antialias:1<Ud[135181],depth:0<Ud[135173],stencil:0<Ud[135174],alpha:0<Ud[135172]}):jc());!g.sf&&d?f=0:(a=new Td(f,a,b,c),f-1==X.length?X.push(a):X[f-1]=a,Y=a,f=a.id)}return f},x:function(){Ud=Xd},Pc:function(a){a:{if(a=Vd(a)){a.wg&&G.get(a.wg)(a.id);X[a.id-1]=null;Y.id==a.id&&(Y=null);for(a=0;a<X.length;a++)if(null!==X[a]){a=void 0;break a}g.sf=void 0}a=void 0}return a},jd:function(a,
b,c){ua(b,Gd,"double");ua(c,Hd,"double")},_c:function(a,b,c){var d=0,e=0;if(a=Vd(a))d=a.width,e=a.height;b&&ua(b,d,"i32");c&&ua(c,e,"i32")},I:function(){if(X)return 1;pc();Ud=Xd;X=[];Y=null;window.addEventListener("gamepadconnected",be,!0);window.addEventListener("gamepaddisconnected",de,!0);window.addEventListener("keydown",ee,!0);window.addEventListener("keypress",$d,!0);window.addEventListener("keyup",fe,!0);window.addEventListener("blur",ge,!0);g.canvas.addEventListener("touchmove",he,!0);g.canvas.addEventListener("touchstart",
le,!0);g.canvas.addEventListener("touchcancel",ne,!0);g.canvas.addEventListener("touchend",ne,!0);g.canvas.addEventListener("mousemove",he,!0);g.canvas.addEventListener("mousedown",le,!0);g.canvas.addEventListener("mouseup",ne,!0);g.canvas.addEventListener("wheel",oe,!0);g.canvas.addEventListener("mousewheel",oe,!0);g.canvas.addEventListener("mouseenter",ie,!0);g.canvas.addEventListener("mouseleave",je,!0);g.canvas.addEventListener("drop",te,!0);g.canvas.addEventListener("dragover",ue,!0);Ld.push(function(a,
b){if(Y){var c=!0;document.fullscreen||document.fullScreen||document.mozFullScreen||document.webkitIsFullScreen?(Y.tg=Y.x,Y.ug=Y.y,Y.sg=Y.width,Y.rg=Y.height,Y.x=Y.y=0,Y.width=screen.width,Y.height=screen.height,Y.Xf=!0):1==Y.Xf?(Y.x=Y.tg,Y.y=Y.ug,Y.width=Y.sg,Y.height=Y.rg,Y.Xf=!1):Y.width!=a||Y.height!=b?(Y.width=a,Y.height=b):c=!1;c&&(Md(Y.width,Y.height,!0),Y&&Y.xg&&G.get(Y.xg)(Y.id,Y.width,Y.height),Y&&Y.Cf&&G.get(Y.Cf)(Y.id,Y.width,Y.height))}});return 1},ve:function(){},na:function(){},$d:function(a,
b){if(a=Vd(a)){var c=a.Bf;a.Bf=b;b=c}else b=null;return b},T:function(a){var b=Wd;Wd=a;return b},ke:function(a,b){a=Vd(a);if(!a)return null;var c=a.Cf;a.Cf=b;return c},Qd:function(a,b){if(a=Vd(a)){var c=a.Df;a.Df=b;b=c}else b=null;return b},ud:function(a,b){if(a=Vd(a)){var c=a.Kf;a.Kf=b;b=c}else b=null;return b},Fd:function(a,b){if(a=Vd(a)){var c=a.Mf;a.Mf=b;b=c}else b=null;return b},ca:function(){},Ec:function(){window.removeEventListener("gamepadconnected",be,!0);window.removeEventListener("gamepaddisconnected",
de,!0);window.removeEventListener("keydown",ee,!0);window.removeEventListener("keypress",$d,!0);window.removeEventListener("keyup",fe,!0);window.removeEventListener("blur",ge,!0);g.canvas.removeEventListener("touchmove",he,!0);g.canvas.removeEventListener("touchstart",le,!0);g.canvas.removeEventListener("touchcancel",ne,!0);g.canvas.removeEventListener("touchend",ne,!0);g.canvas.removeEventListener("mousemove",he,!0);g.canvas.removeEventListener("mousedown",le,!0);g.canvas.removeEventListener("mouseup",
ne,!0);g.canvas.removeEventListener("wheel",oe,!0);g.canvas.removeEventListener("mousewheel",oe,!0);g.canvas.removeEventListener("mouseenter",ie,!0);g.canvas.removeEventListener("mouseleave",je,!0);g.canvas.removeEventListener("drop",te,!0);g.canvas.removeEventListener("dragover",ue,!0);g.canvas.width=g.canvas.height=1;Y=X=null},f:function(a,b){Ud[a]=b},k:function(){},e:function(){return 0}};
(function(){function a(e){g.asm=e.exports;ya=g.asm.Re;La();G=g.asm._e;Na.unshift(g.asm.Se);Va("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return Za().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){h("failed to asynchronously prepare wasm: "+f);p(f)})}var d={a:Ae};Ua("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return h("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ta||"function"!==
typeof WebAssembly.instantiateStreaming||Wa()||I.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(I,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){h("wasm streaming compile failed: "+f);h("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Se).apply(null,arguments)};
var se=g._free=function(){return(se=g._free=g.asm.Te).apply(null,arguments)},Ca=g._malloc=function(){return(Ca=g._malloc=g.asm.Ue).apply(null,arguments)};g._main=function(){return(g._main=g.asm.Ve).apply(null,arguments)};
var xe=g.___errno_location=function(){return(xe=g.___errno_location=g.asm.We).apply(null,arguments)},ze=g._memset=function(){return(ze=g._memset=g.asm.Xe).apply(null,arguments)},Ia=g.stackAlloc=function(){return(Ia=g.stackAlloc=g.asm.Ye).apply(null,arguments)},ye=g._memalign=function(){return(ye=g._memalign=g.asm.Ze).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.$e).apply(null,arguments)};g.dynCall_ji=function(){return(g.dynCall_ji=g.asm.af).apply(null,arguments)};
g.addRunDependency=Ua;g.removeRunDependency=Va;g.FS_createPath=cc;g.FS_createDataFile=ec;g.FS_createPreloadedFile=ic;g.FS_createLazyFile=hc;g.FS_createDevice=M;g.FS_unlink=Tb;var Be;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ta=function Ce(){Be||De();Be||(Ta=Ce)};
function De(a){function b(){if(!Be&&(Be=!0,g.calledRun=!0,!za)){g.noFSInit||ac||(ac=!0,$b(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?M("/dev","stdin",g.stdin):Sb("/dev/tty","/dev/stdin"),g.stdout?M("/dev","stdout",null,g.stdout):Sb("/dev/tty","/dev/stdout"),g.stderr?M("/dev","stderr",null,g.stderr):Sb("/dev/tty1","/dev/stderr"),Vb("/dev/stdin",0),Vb("/dev/stdout",1),Vb("/dev/stderr",1));eb(Na);Bb=!1;eb(Oa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ee){var c=a,d=g._main;
c=c||[];var e=c.length+1,f=Ia(4*(e+1));v[f>>2]=Ha(da);for(var k=1;k<e;k++)v[(f>>2)+k]=Ha(c[k-1]);v[(f>>2)+e]=0;try{var l=d(e,f);Pd(l,!0)}catch(m){m instanceof pa||"unwind"==m||((c=m)&&"object"===typeof m&&m.stack&&(c=[m,m.stack]),h("exception thrown: "+c),ea(1,m))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),Pa.unshift(c);eb(Pa)}}a=a||ca;if(!(0<Ra)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Qa();
eb(Ma);0<Ra||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=De;function Pd(a,b){Aa=a;if(!b||!noExitRuntime||0!==a){if(!noExitRuntime){if(g.onExit)g.onExit(a);za=!0}ea(a,new pa(a))}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ee=!0;g.noInitialRun&&(Ee=!1);De();
